version: 2

updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tehran"
    open-pull-requests-limit: 10
    reviewers:
      - "medogram-team"
    assignees:
      - "medogram-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated-pr"
    # Group updates by dependency type
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "eslint*"
          - "tailwindcss*"
          - "postcss*"
          - "autoprefixer*"
        update-types:
          - "minor"
          - "patch"
      ui-libraries:
        patterns:
          - "@headlessui/*"
          - "@heroicons/*"
          - "framer-motion*"
          - "lucide-react*"
        update-types:
          - "minor"
          - "patch"
      form-validation:
        patterns:
          - "react-hook-form*"
          - "@hookform/*"
          - "yup*"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific packages if needed
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # Ignore specific versions with known issues
      # - dependency-name: "example-package"
      #   versions: ["1.2.3", "1.2.4"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Tehran"
    open-pull-requests-limit: 5
    reviewers:
      - "medogram-team"
    assignees:
      - "medogram-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci-cd"
      - "automated-pr"

  # Docker (if using Docker in the future)
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "tuesday"
  #     time: "09:00"
  #     timezone: "Asia/Tehran"
  #   open-pull-requests-limit: 3
  #   reviewers:
  #     - "medogram-team"
  #   commit-message:
  #     prefix: "docker"
  #   labels:
  #     - "docker"
  #     - "automated-pr"